### ISSUE TITLE
BizTalkHostInstance problem

### ISSUE THREAD

**Issue by IlleNilsson** [blackmarble/BizTalkServer#5]
VERBOSE: [[Computer Name]]: [[BizTalkServerHostInstance]GcSxPrioHost64] Importing the module  BizTalkServer in force mode.
Access denied
+ CategoryInfo : PermissionDenied: (:) [], CimException  + FullyQualifiedErrorId : HRESULT 0x80041003,Microsoft.Management.Infrastructure.CimCmdlets.NewCimSessionCommand
+ PSComputerName : [Computer Name]
VERBOSE: [[Computer Name]]: [[BizTalkServerHostInstance]GcSxPrioHost64] Operation '' complete.
Cannot bind argument to parameter 'CimSession' because it is null.
+ CategoryInfo : InvalidData: (:) [], CimException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand
+ PSComputerName        : [Computer Name]

**Comment by rfennell** [comment]
This module has not been under active usage by us for a while as we have moved the majority of our projects to Azure Logic Apps. The project should have been marked as a read-only archive.

That said, the error you report looks like a permission error importing the PS module. We don't think that's anything to do with the specific DSC code in the module.

We would suggest manually trying to import the module on the same VM you are trying to use DSC on and resolve any errors you are getting.

Sorry, don't have anything more specific, but it as a general PS Module import error look for missing dependencies or reboots required.
